name: MindGames
favicon: null
layout_spectrum: 0.91538
typography_spectrum: 0.29703
title: Mind Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cc0000'
    - '#a2953f'
    - '#83afb7'
    - '#543012'
  brandStrength: 0.3646935608703643
  lightness: 0.36591867194510996
  saturation: 0.3812136184424162
  rhythmicContrast: 0.32287026359699667
purpose: []
